# Generated by Django 3.2.13 on 2023-12-29 00:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=3)),
                ('nickname', models.CharField(max_length=255)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=255, null=True)),
                ('championships', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), blank=True, null=True, size=None)),
                ('ls_hits', models.IntegerField(blank=True, null=True)),
                ('ls_2b', models.IntegerField(blank=True, null=True)),
                ('ls_3b', models.IntegerField(blank=True, null=True)),
                ('ls_hr', models.IntegerField(blank=True, null=True)),
                ('ls_sb', models.IntegerField(blank=True, null=True)),
                ('ls_runs', models.IntegerField(blank=True, null=True)),
                ('ls_rbi', models.IntegerField(blank=True, null=True)),
                ('ls_k', models.IntegerField(blank=True, null=True)),
                ('ls_bb', models.IntegerField(blank=True, null=True)),
                ('ls_plate_appearances', models.IntegerField(blank=True, null=True)),
                ('ls_ab', models.IntegerField(blank=True, null=True)),
                ('ls_avg', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('ls_obp', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('ls_slg', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('ls_iso', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('ls_k_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('ls_bb_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('ls_g', models.IntegerField(blank=True, null=True)),
                ('ls_gs', models.IntegerField(blank=True, null=True)),
                ('ls_ip', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ls_pk', models.IntegerField(blank=True, null=True)),
                ('ls_pbb', models.IntegerField(blank=True, null=True)),
                ('ls_ha', models.IntegerField(blank=True, null=True)),
                ('ls_hra', models.IntegerField(blank=True, null=True)),
                ('ls_er', models.IntegerField(blank=True, null=True)),
                ('ls_k_9', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ls_hits_9', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ls_bb_9', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ls_hr_9', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ls_era', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ls_whip', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('owner_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statsdb.owner')),
            ],
            options={
                'ordering': ['abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('IF', 'Infield'), ('OF', 'Outfield'), ('IF-OF', 'Infield/Outfield'), ('OF-P', 'Pitcher/Outfield'), ('IF-P', 'Pitcher/Infield')], max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('birthdate_qa', models.BooleanField(default=False)),
                ('raw_age', models.IntegerField(blank=True, default=None, null=True)),
                ('ba_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mlbam_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mlb_dotcom', models.CharField(blank=True, max_length=255, null=True)),
                ('bp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bref_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fantrax_id', models.CharField(blank=True, max_length=255, null=True)),
                ('baseballcube_id', models.CharField(blank=True, max_length=255, null=True)),
                ('perfectgame_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ba_url', models.CharField(blank=True, max_length=255, null=True)),
                ('bref_url', models.CharField(blank=True, max_length=255, null=True)),
                ('bref_img', models.CharField(blank=True, max_length=255, null=True)),
                ('fg_url', models.CharField(blank=True, max_length=255, null=True)),
                ('mlb_dotcom_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fantrax_url', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_owned', models.BooleanField(default=False)),
                ('is_mlb_roster', models.BooleanField(default=False)),
                ('is_aaa_roster', models.BooleanField(default=False)),
                ('is_35man_roster', models.BooleanField(default=False)),
                ('cs_pa', models.IntegerField(blank=True, null=True)),
                ('cs_gp', models.IntegerField(blank=True, null=True)),
                ('cs_st', models.IntegerField(blank=True, null=True)),
                ('cs_ip', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statsdb.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
