# Generated by Django 3.2.13 on 2023-12-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
