# Generated by Django 3.2.13 on 2024-01-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battingstatline',
            old_name='assblood',
            new_name='rl2o',
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='cycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='gidp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='k_looking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='outfield_assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='po',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
