# Generated by Django 5.0 on 2024-01-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0002_auto_20240115_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingstatline',
            name='outs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='player_mlbam_id',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
    ]
