# Generated by Django 3.2.13 on 2023-12-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0002_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='injury_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_bench',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_bullpen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_injured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_mlb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_mlb40man',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_player_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='mlb_org',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='role_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='roster_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
