# Generated by Django 5.0 on 2024-02-19 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battingstatline',
            old_name='_id',
            new_name='pk_id',
        ),
        migrations.RemoveField(
            model_name='battingstatline',
            name='FAN_total',
        ),
    ]
