# Generated by Django 5.0 on 2024-01-17 02:37

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0003_battingstatline_outs_battingstatline_player_mlbam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_bb',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('bb'), '*', models.Value(-1)), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_outs',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('outs'), '*', models.Value(0.75)), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_triples',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('triples'), '*', models.Value(-3)), output_field=models.IntegerField()),
        ),
    ]
