# Generated by Django 3.2.13 on 2023-12-29 15:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0003_auto_20231228_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('P', 'Pitcher'), ('SP', 'Starter'), ('RP', 'Reliever'), ('C', 'Catcher'), ('IF', 'Infield'), ('OF', 'Outfield'), ('1B', 'First base'), ('2B', 'Second base'), ('SS', 'Shortstop'), ('3B', 'Third base'), ('LF', 'Left field'), ('CF', 'Center field'), ('RF', 'Right field'), ('IF-OF', 'IF-OF'), ('OF-P', 'OF-P'), ('IF-P', 'IF-P')], max_length=255, null=True),
        ),
    ]
