# Generated by Django 5.0 on 2024-02-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0003_rename__id_battingstatline_pk_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_total',
            field=models.FloatField(default=0.0),
        ),
    ]
