# Generated by Django 3.2.13 on 2023-12-31 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0004_auto_20231229_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ba_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ba_url',
        ),
        migrations.RemoveField(
            model_name='player',
            name='baseballcube_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bp_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fantrax_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fantrax_url',
        ),
        migrations.RemoveField(
            model_name='player',
            name='perfectgame_id',
        ),
    ]
