# Generated by Django 5.0 on 2024-01-17 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0004_battingstatline_fan_bb_battingstatline_fan_outs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battingstatline',
            name='FAN_bb',
        ),
        migrations.RemoveField(
            model_name='battingstatline',
            name='FAN_outs',
        ),
        migrations.RemoveField(
            model_name='battingstatline',
            name='FAN_triples',
        ),
    ]
