# Generated by Django 3.2.13 on 2023-12-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0005_auto_20231230_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattingStatLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('player', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('avg', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('obp', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('slg', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('batting_order', models.IntegerField(null=True)),
                ('ab', models.IntegerField(null=True)),
                ('r', models.IntegerField(null=True)),
                ('h', models.IntegerField(null=True)),
                ('doubles', models.IntegerField(null=True)),
                ('triples', models.IntegerField(null=True)),
                ('hr', models.IntegerField(null=True)),
                ('rbi', models.IntegerField(null=True)),
                ('bb', models.IntegerField(null=True)),
                ('k', models.IntegerField(null=True)),
                ('lob', models.IntegerField(null=True)),
                ('sb', models.IntegerField(null=True)),
                ('cs', models.IntegerField(null=True)),
                ('e', models.IntegerField(null=True)),
                ('assblood', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PitchingStatLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('player', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('ip', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('h', models.IntegerField(null=True)),
                ('r', models.IntegerField(null=True)),
                ('er', models.IntegerField(null=True)),
                ('bb', models.IntegerField(null=True)),
                ('k', models.IntegerField(null=True)),
                ('hr', models.IntegerField(null=True)),
                ('bf', models.IntegerField(null=True)),
                ('balks', models.IntegerField(null=True)),
                ('qs', models.BooleanField(null=True)),
                ('perfect_game', models.BooleanField(null=True)),
                ('no_hitter', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
