# Generated by Django 5.0 on 2024-02-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0005_seasonbattingstatline'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonbattingstatline',
            name='player_mlbam_id',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
