# Generated by Django 5.0 on 2024-01-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0006_auto_20240116_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_outs',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('outs'), function='fan_outs'), output_field=models.FloatField()),
        ),
    ]
