# Generated by Django 5.0 on 2024-03-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0006_seasonbattingstatline_player_mlbam_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonbattingstatline',
            old_name='FAN_h',
            new_name='FAN_hits',
        ),
    ]
