# Generated by Django 3.2.13 on 2023-12-31 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0007_auto_20231230_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingstatline',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statsdb.player'),
        ),
        migrations.AlterField(
            model_name='pitchingstatline',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statsdb.player'),
        ),
    ]
