# Generated by Django 5.0 on 2024-01-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0007_battingstatline_fan_outs'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_hits',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('h'), function='fan_hits'), output_field=models.FloatField()),
        ),
    ]
