# Generated by Django 5.0 on 2024-03-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0008_alter_seasonbattingstatline_cycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battingstatline',
            old_name='FAN_hits',
            new_name='FAN_h',
        ),
        migrations.RenameField(
            model_name='seasonbattingstatline',
            old_name='FAN_hits',
            new_name='FAN_h',
        ),
    ]
