# Generated by Django 5.0 on 2024-01-17 03:42

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0008_battingstatline_fan_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_bb',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('bb'), '*', models.Value(-1)), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_triples',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('triples'), '*', models.Value(-3)), output_field=models.IntegerField()),
        ),
    ]
