# Generated by Django 3.2.13 on 2023-12-31 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0009_auto_20231230_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battingstatline',
            name='player',
        ),
        migrations.RemoveField(
            model_name='pitchingstatline',
            name='player',
        ),
    ]
