# Generated by Django 5.0 on 2024-01-18 00:46

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0009_battingstatline_fan_bb_battingstatline_fan_triples'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_cs',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('cs'), '*', models.Value(2)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_cycle',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('cycle'), function='fan_cycle'), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_doubles',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('doubles'), '*', models.Value(-2)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_e',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('e'), '*', models.Value(2)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_gidp',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('gidp'), '*', models.Value(2)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_hr',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('hr'), function='fan_hr'), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_k',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('k'), function='fan_k'), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_k_looking',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('k_looking'), '*', models.Value(0.5)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_lob',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('lob'), '*', models.Value(0.5)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_outfield_assists',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('outfield_assists'), '*', models.Value(-1)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_po',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('po'), '*', models.Value(4)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_r',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('r'), '*', models.Value(-1)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_rbi',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('rbi'), '*', models.Value(-1)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_rl2o',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('rl2o'), '*', models.Value(2)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='FAN_sb',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('sb'), '*', models.Value(-3)), output_field=models.FloatField()),
        ),
        migrations.AlterField(
            model_name='battingstatline',
            name='FAN_bb',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('bb'), '*', models.Value(-1)), output_field=models.FloatField()),
        ),
        migrations.AlterField(
            model_name='battingstatline',
            name='FAN_triples',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('triples'), '*', models.Value(-3)), output_field=models.FloatField()),
        ),
    ]
