# Generated by Django 5.0 on 2024-03-09 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0010_teambattingstatline'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingstatline',
            name='fantasy_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='statsdb.team'),
        ),
    ]
