# Generated by Django 5.0 on 2024-03-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0011_battingstatline_fantasy_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PitchingStatLine',
        ),
    ]
