# Generated by Django 5.0 on 2024-03-09 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0012_delete_pitchingstatline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchingStatLine',
            fields=[
                ('pk_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('player_mlbam_id', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('ip', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('h', models.IntegerField(blank=True, null=True)),
                ('r', models.IntegerField(blank=True, null=True)),
                ('er', models.IntegerField(blank=True, null=True)),
                ('bb', models.IntegerField(blank=True, null=True)),
                ('k', models.IntegerField(blank=True, null=True)),
                ('hr', models.IntegerField(blank=True, null=True)),
                ('bf', models.IntegerField(blank=True, null=True)),
                ('balks', models.IntegerField(blank=True, null=True)),
                ('qs', models.BooleanField(null=True)),
                ('perfect_game', models.BooleanField(null=True)),
                ('no_hitter', models.BooleanField(null=True)),
                ('fantasy_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='statsdb.team')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statsdb.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
