# Generated by Django 5.0 on 2024-03-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0013_pitchingstatline'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchingstatline',
            name='bs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
