# Generated by Django 5.0 on 2024-03-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0015_rename_id_pitchingstatline_statline_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchingstatline',
            name='wp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
