# Generated by Django 5.0 on 2024-03-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0016_pitchingstatline_wp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitchingstatline',
            old_name='qs',
            new_name='quality_start',
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='bra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='dpi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='e',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='hb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='ir',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='irs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='relief_loss',
            field=models.BooleanField(null=True),
        ),
    ]
