# Generated by Django 5.0 on 2024-03-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0017_rename_qs_pitchingstatline_quality_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatline',
            name='bs',
            field=models.BooleanField(null=True),
        ),
    ]
