# Generated by Django 3.2.13 on 2024-01-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0017_team_lineup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingstatline',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statsdb.player'),
        ),
    ]
