# Generated by Django 3.2.13 on 2024-01-05 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0018_alter_battingstatline_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lineup_1B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_1B', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_2B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_2B', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_3B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_3B', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_C',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_C', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_CF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_CF', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_LF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_LF', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_RF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_RF', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_RP1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_RP1', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_RP2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_RP2', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_RP3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_RP3', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_SP1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_SP1', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_SP2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_SP2', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_SP3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_SP3', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_SP4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_SP4', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_SP5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_SP5', to='statsdb.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_SS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_SS', to='statsdb.player'),
        ),
    ]
