# Generated by Django 5.0 on 2024-03-10 19:18

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0018_alter_pitchingstatline_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_balks',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('balks'), '*', models.Value(5)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_bb',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('bb'), '*', models.Value(0.5)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_bra',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('bra'), '*', models.Value(1)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_bs',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('bs'), function='fan_bs'), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_dpi',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('dpi'), '*', models.Value(-1)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_e',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('e'), '*', models.Value(1)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_er',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('er'), '*', models.Value(1)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_h',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('h'), '*', models.Value(0.5)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_hb',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('hb'), '*', models.Value(1)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_hr',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('hr'), function='fan_hr_pitch'), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_ip',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('ip'), '*', models.Value(-1.5)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_ir',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('ir'), '*', models.Value(5)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_irs',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('irs'), '*', models.Value(-5)), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_k',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('k'), function='fan_k_pitch'), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_no_hitter',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('no_hitter'), function='fan_no_hitter'), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_perfect_game',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('perfect_game'), function='fan_perfect_game'), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_relief_loss',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('relief_loss'), function='fan_relief_loss'), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_wp',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('wp'), '*', models.Value(2)), output_field=models.FloatField()),
        ),
    ]
