# Generated by Django 3.2.13 on 2024-01-06 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0019_auto_20240105_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='lineup',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_1B',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_2B',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_3B',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_C',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_CF',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_LF',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_RF',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_RP1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_RP2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_RP3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_SP1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_SP2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_SP3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_SP4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_SP5',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lineup_SS',
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('lineup_1B', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_1B', to='statsdb.player')),
                ('lineup_2B', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_2B', to='statsdb.player')),
                ('lineup_3B', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_3B', to='statsdb.player')),
                ('lineup_C', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_C', to='statsdb.player')),
                ('lineup_CF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_CF', to='statsdb.player')),
                ('lineup_LF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_LF', to='statsdb.player')),
                ('lineup_RF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_RF', to='statsdb.player')),
                ('lineup_RP1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_RP1', to='statsdb.player')),
                ('lineup_RP2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_RP2', to='statsdb.player')),
                ('lineup_RP3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_RP3', to='statsdb.player')),
                ('lineup_SP1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_SP1', to='statsdb.player')),
                ('lineup_SP2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_SP2', to='statsdb.player')),
                ('lineup_SP3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_SP3', to='statsdb.player')),
                ('lineup_SP4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_SP4', to='statsdb.player')),
                ('lineup_SP5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_SP5', to='statsdb.player')),
                ('lineup_SS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_SS', to='statsdb.player')),
                ('lineup_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsdb.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='team',
            name='team_lineup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statsdb.lineup'),
        ),
    ]
