# Generated by Django 5.0 on 2024-03-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0020_seasonpitchingstatline_teampitchingstatline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitchingstatline',
            name='FAN_ip',
        ),
    ]
