# Generated by Django 5.0 on 2024-03-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0021_remove_pitchingstatline_fan_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchingstatline',
            name='FAN_ip',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('ip'), function='fan_ip'), output_field=models.FloatField()),
        ),
    ]
