# Generated by Django 5.0 on 2024-03-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0022_pitchingstatline_fan_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatline',
            name='ip',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
