# Generated by Django 5.0 on 2024-03-10 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0023_alter_pitchingstatline_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonpitchingstatline',
            name='bs',
        ),
        migrations.RemoveField(
            model_name='seasonpitchingstatline',
            name='no_hitter',
        ),
        migrations.RemoveField(
            model_name='seasonpitchingstatline',
            name='perfect_game',
        ),
        migrations.RemoveField(
            model_name='seasonpitchingstatline',
            name='quality_start',
        ),
        migrations.RemoveField(
            model_name='seasonpitchingstatline',
            name='relief_loss',
        ),
    ]
