# Generated by Django 5.0 on 2024-03-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0024_remove_seasonpitchingstatline_bs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonpitchingstatline',
            name='bs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='seasonpitchingstatline',
            name='no_hitter',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='seasonpitchingstatline',
            name='perfect_game',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='seasonpitchingstatline',
            name='quality_start',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='seasonpitchingstatline',
            name='relief_loss',
            field=models.FloatField(null=True),
        ),
    ]
