# Generated by Django 5.0 on 2024-03-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0025_seasonpitchingstatline_bs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatline',
            name='FAN_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='seasonbattingstatline',
            name='FAN_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='seasonpitchingstatline',
            name='FAN_ip',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='seasonpitchingstatline',
            name='FAN_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='teambattingstatline',
            name='FAN_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='teampitchingstatline',
            name='FAN_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
