# Generated by Django 5.0 on 2026-03-06 20:59
# Fixed: GeneratedField cannot be altered in-place; use SeparateDatabaseAndState
# to update Django's migration state without touching the existing DB column.

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0027_rename_is_mlb_roster_player_is_fantasy_roster'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='pitchingstatline',
                    name='FAN_bb',
                    field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('bb'), '*', models.Value(1)), output_field=models.FloatField()),
                ),
                migrations.AlterField(
                    model_name='pitchingstatline',
                    name='FAN_h',
                    field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('h'), '*', models.Value(1)), output_field=models.FloatField()),
                ),
            ],
        ),
    ]
