# Generated by Django 5.0 on 2026-03-16 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsdb', '0044_update_fan_rl2o'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('transaction_type', models.CharField(choices=[('add', 'Add'), ('drop', 'Drop')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsdb.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsdb.team')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
