services:
  django:
    container_name: statsdb
    build: app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./app:/app
    x-develop:
        - action: rebuild
          path: requirements.txt
    ports:
      - "8000:8000"
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
  frontend:
    container_name: ballgame
    build: ./app/ballgame
    volumes: 
      - ./app/ballgame:/app/ballgame
    ports:
      - "5173:5173"
    stdin_open: true
    command: npm run dev